services:
  - type: web
    name: travel-planner
    runtime: docker
    repo: https://github.com/Vinaykumarreddy467/Travel_Planner.git
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: OWM_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
