services:
  - type: web
    name: travel-planner
    runtime: python
    repo: https://github.com/Vinaykumarreddy467/Travel_Planner.git
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: OWM_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
